// generated from spec: pcd-lint.md sha256:293541ab62274835c61de50947f6283748831c4681cf3f02c4be2f8e942d28a9

// Package spdx provides validation of SPDX license identifiers.
// The license list is embedded at build time per the pcd-lint specification.
package spdx

import "strings"

// Version is the embedded SPDX license list version.
const Version = "3.23"

// validIdentifiers is the set of known SPDX license identifiers.
// Source: https://spdx.org/licenses/ (SPDX License List 3.23)
// This is a representative subset covering the most common licenses.
// The full list is embedded here for offline validation.
var validIdentifiers = map[string]bool{
	"0BSD":                                true,
	"AAL":                                 true,
	"Abstyles":                            true,
	"AdaCore-doc":                         true,
	"Adobe-2006":                          true,
	"Adobe-Glyph":                         true,
	"ADSL":                                true,
	"AFL-1.1":                             true,
	"AFL-1.2":                             true,
	"AFL-2.0":                             true,
	"AFL-2.1":                             true,
	"AFL-3.0":                             true,
	"Agpl-3.0":                            false, // wrong case
	"AGPL-1.0-only":                       true,
	"AGPL-1.0-or-later":                   true,
	"AGPL-3.0-only":                       true,
	"AGPL-3.0-or-later":                   true,
	"Aladdin":                             true,
	"AMDPLPA":                             true,
	"AML":                                 true,
	"AMPAS":                               true,
	"ANTLR-PD":                            true,
	"ANTLR-PD-fallback":                   true,
	"Apache-1.0":                          true,
	"Apache-1.1":                          true,
	"Apache-2.0":                          true,
	"APAFML":                              true,
	"APL-1.0":                             true,
	"App-s2p":                             true,
	"APSL-1.0":                            true,
	"APSL-1.1":                            true,
	"APSL-1.2":                            true,
	"APSL-2.0":                            true,
	"Arphic-1999":                         true,
	"Artistic-1.0":                        true,
	"Artistic-1.0-cl8":                    true,
	"Artistic-1.0-Perl":                   true,
	"Artistic-2.0":                        true,
	"ASWF-Digital-Assets-1.0":             true,
	"ASWF-Digital-Assets-1.1":             true,
	"Beerware":                            true,
	"Bitstream-Charter":                   true,
	"Bitstream-Vera":                      true,
	"BitTorrent-1.0":                      true,
	"BitTorrent-1.1":                      true,
	"blessing":                            true,
	"BlueOak-1.0.0":                       true,
	"Borceux":                             true,
	"BSD-1-Clause":                        true,
	"BSD-2-Clause":                        true,
	"BSD-2-Clause-Patent":                 true,
	"BSD-2-Clause-Views":                  true,
	"BSD-3-Clause":                        true,
	"BSD-3-Clause-Clear":                  true,
	"BSD-3-Clause-LBNL":                   true,
	"BSD-3-Clause-Modification":           true,
	"BSD-3-Clause-No-Nuclear-License":     true,
	"BSD-3-Clause-No-Nuclear-License-2014": true,
	"BSD-3-Clause-No-Nuclear-Warranty":    true,
	"BSD-3-Clause-Open-MPI":               true,
	"BSD-4-Clause":                        true,
	"BSD-4-Clause-Shortened":              true,
	"BSD-4-Clause-UC":                     true,
	"BSD-4.3RENO":                         true,
	"BSD-4.3TAHOE":                        true,
	"BSD-Advertising-Acknowledgement":     true,
	"BSD-Attribution-HPND-disclaimer":     true,
	"BSD-Protection":                      true,
	"BSD-Source-Code":                     true,
	"BSL-1.0":                             true,
	"BUSL-1.1":                            true,
	"Cal-1.0":                             true,
	"Cal-1.0-Combined-Work-Exception":     true,
	"Caldera":                             true,
	"CATOSL-1.1":                          true,
	"CC-BY-1.0":                           true,
	"CC-BY-2.0":                           true,
	"CC-BY-2.5":                           true,
	"CC-BY-2.5-AU":                        true,
	"CC-BY-3.0":                           true,
	"CC-BY-3.0-AT":                        true,
	"CC-BY-3.0-DE":                        true,
	"CC-BY-3.0-IGO":                       true,
	"CC-BY-3.0-NL":                        true,
	"CC-BY-3.0-US":                        true,
	"CC-BY-4.0":                           true,
	"CC-BY-NC-1.0":                        true,
	"CC-BY-NC-2.0":                        true,
	"CC-BY-NC-2.5":                        true,
	"CC-BY-NC-3.0":                        true,
	"CC-BY-NC-4.0":                        true,
	"CC-BY-NC-ND-1.0":                     true,
	"CC-BY-NC-ND-2.0":                     true,
	"CC-BY-NC-ND-2.5":                     true,
	"CC-BY-NC-ND-3.0":                     true,
	"CC-BY-NC-ND-3.0-IGO":                 true,
	"CC-BY-NC-ND-4.0":                     true,
	"CC-BY-NC-SA-1.0":                     true,
	"CC-BY-NC-SA-2.0":                     true,
	"CC-BY-NC-SA-2.0-DE":                  true,
	"CC-BY-NC-SA-2.0-FR":                  true,
	"CC-BY-NC-SA-2.0-UK":                  true,
	"CC-BY-NC-SA-2.5":                     true,
	"CC-BY-NC-SA-3.0":                     true,
	"CC-BY-NC-SA-3.0-IGO":                 true,
	"CC-BY-NC-SA-4.0":                     true,
	"CC-BY-ND-1.0":                        true,
	"CC-BY-ND-2.0":                        true,
	"CC-BY-ND-2.5":                        true,
	"CC-BY-ND-3.0":                        true,
	"CC-BY-ND-3.0-IGO":                    true,
	"CC-BY-ND-4.0":                        true,
	"CC-BY-SA-1.0":                        true,
	"CC-BY-SA-2.0":                        true,
	"CC-BY-SA-2.0-UK":                     true,
	"CC-BY-SA-2.1-JP":                     true,
	"CC-BY-SA-2.5":                        true,
	"CC-BY-SA-3.0":                        true,
	"CC-BY-SA-3.0-AT":                     true,
	"CC-BY-SA-3.0-DE":                     true,
	"CC-BY-SA-3.0-IGO":                    true,
	"CC-BY-SA-4.0":                        true,
	"CC-PDDC":                             true,
	"CC0-1.0":                             true,
	"CDDL-1.0":                            true,
	"CDDL-1.1":                            true,
	"CDL-1.0":                             true,
	"CDLA-Permissive-1.0":                 true,
	"CDLA-Permissive-2.0":                 true,
	"CDLA-Sharing-1.0":                    true,
	"CECILL-1.0":                          true,
	"CECILL-1.1":                          true,
	"CECILL-2.0":                          true,
	"CECILL-2.1":                          true,
	"CECILL-B":                            true,
	"CECILL-C":                            true,
	"CERN-OHL-P-2.0":                      true,
	"CERN-OHL-S-2.0":                      true,
	"CERN-OHL-W-2.0":                      true,
	"CFITSIO":                             true,
	"checkmk":                             true,
	"ClArtistic":                          true,
	"Clips":                               true,
	"CMU-Mach":                            true,
	"CNRI-Jython":                         true,
	"CNRI-Python":                         true,
	"CNRI-Python-GPL-Compatible":          true,
	"COIL-1.0":                            true,
	"Community-Spec-1.0":                  true,
	"Condor-1.1":                          true,
	"copyleft-next-0.3.0":                 true,
	"copyleft-next-0.3.1":                 true,
	"Cornell-Lossless-JPEG":               true,
	"CPAL-1.0":                            true,
	"CPL-1.0":                             true,
	"CPOL-1.02":                           true,
	"Crossword":                           true,
	"CrystalStacker":                      true,
	"CUA-OPL-1.0":                         true,
	"Cube":                                true,
	"curl":                                true,
	"D-FSL-1.0":                           true,
	"diffmark":                            true,
	"DL-DE-BY-2.0":                        true,
	"DOC":                                 true,
	"Dotseqn":                             true,
	"DRL-1.0":                             true,
	"DSDP":                                true,
	"dtoa":                                true,
	"dvipdfm":                             true,
	"ECL-1.0":                             true,
	"ECL-2.0":                             true,
	"EFL-1.0":                             true,
	"EFL-2.0":                             true,
	"elastic-2.0":                         true,
	"Entessa":                             true,
	"EPICS":                               true,
	"EPL-1.0":                             true,
	"EPL-2.0":                             true,
	"ErlPL-1.1":                           true,
	"etalab-2.0":                          true,
	"EUDatagrid":                          true,
	"EUPL-1.0":                            true,
	"EUPL-1.1":                            true,
	"EUPL-1.2":                            true,
	"Eurosym":                             true,
	"Fair":                                true,
	"FDK-AAC":                             true,
	"Frameworx-1.0":                       true,
	"FreeBSD-DOC":                         true,
	"FreeImage":                           true,
	"FSFAP":                               true,
	"FSFUL":                               true,
	"FSFULLWD":                            true,
	"FTL":                                 true,
	"GD":                                  true,
	"GFDL-1.1-invariants-only":            true,
	"GFDL-1.1-invariants-or-later":        true,
	"GFDL-1.1-no-invariants-only":         true,
	"GFDL-1.1-no-invariants-or-later":     true,
	"GFDL-1.1-only":                       true,
	"GFDL-1.1-or-later":                   true,
	"GFDL-1.2-invariants-only":            true,
	"GFDL-1.2-invariants-or-later":        true,
	"GFDL-1.2-no-invariants-only":         true,
	"GFDL-1.2-no-invariants-or-later":     true,
	"GFDL-1.2-only":                       true,
	"GFDL-1.2-or-later":                   true,
	"GFDL-1.3-invariants-only":            true,
	"GFDL-1.3-invariants-or-later":        true,
	"GFDL-1.3-no-invariants-only":         true,
	"GFDL-1.3-no-invariants-or-later":     true,
	"GFDL-1.3-only":                       true,
	"GFDL-1.3-or-later":                   true,
	"Giftware":                            true,
	"GL2PS":                               true,
	"Glide":                               true,
	"Glulxe":                              true,
	"GLWTPL":                              true,
	"gnuplot":                             true,
	"GPL-2.0-only":                        true,
	"GPL-2.0-or-later":                    true,
	"GPL-3.0-only":                        true,
	"GPL-3.0-or-later":                    true,
	"Graphics-Gems":                       true,
	"gSOAP-1.3b":                          true,
	"HaskellReport":                       true,
	"Hippocratic-2.1":                     true,
	"HP-1986":                             true,
	"HPND":                                true,
	"HPND-Markus-Kuhn":                    true,
	"HPND-sell-variant":                   true,
	"HPND-sell-variant-MIT-disclaimer":    true,
	"HTMLTIDY":                            true,
	"IBM-pibs":                            true,
	"ICU":                                 true,
	"IEC-Code-Components-EULA":            true,
	"IJG":                                 true,
	"IJG-short":                           true,
	"ImageMagick":                         true,
	"iMatix":                              true,
	"Imlib2":                              true,
	"Info-ZIP":                            true,
	"Inner-Net-2.0":                       true,
	"Intel":                               true,
	"Intel-ACPI":                          true,
	"Interbase-1.0":                       true,
	"IPA":                                 true,
	"IPL-1.0":                             true,
	"ISC":                                 true,
	"Jam":                                 true,
	"JasPer-2.0":                          true,
	"JPL-image":                           true,
	"JPNIC":                               true,
	"JSON":                                true,
	"Kazlib":                              true,
	"Knuth-CTAN":                          true,
	"LAL-1.2":                             true,
	"LAL-1.3":                             true,
	"Latex2e":                             true,
	"Latex2e-translated-notice":           true,
	"Leptonica":                           true,
	"LGPL-2.0-only":                       true,
	"LGPL-2.0-or-later":                   true,
	"LGPL-2.1-only":                       true,
	"LGPL-2.1-or-later":                   true,
	"LGPL-3.0-only":                       true,
	"LGPL-3.0-or-later":                   true,
	"LGPLLR":                              true,
	"Libpng":                              true,
	"libpng-2.0":                          true,
	"libselinux-1.0":                      true,
	"libtiff":                             true,
	"LiLiQ-P-1.1":                        true,
	"LiLiQ-R-1.1":                        true,
	"LiLiQ-Rplus-1.1":                    true,
	"Linux-man-pages-1-para":              true,
	"Linux-man-pages-copyleft":            true,
	"Linux-man-pages-copyleft-2-para":     true,
	"Linux-man-pages-copyleft-var":        true,
	"Linux-OpenIB":                        true,
	"LOOP":                                true,
	"LPL-1.0":                             true,
	"LPL-1.02":                            true,
	"LPPL-1.0":                            true,
	"LPPL-1.1":                            true,
	"LPPL-1.2":                            true,
	"LPPL-1.3a":                           true,
	"LPPL-1.3c":                           true,
	"MakeIndex":                           true,
	"Martin-Ack":                          true,
	"Minpack":                             true,
	"MirOS":                               true,
	"MIT":                                 true,
	"MIT-0":                               true,
	"MIT-advertising":                     true,
	"MIT-CMU":                             true,
	"MIT-enna":                            true,
	"MIT-feh":                             true,
	"MIT-Festival":                        true,
	"MIT-Modern-Variant":                  true,
	"MIT-open-group":                      true,
	"MIT-Wu":                              true,
	"MITNFA":                              true,
	"Motosoto":                            true,
	"Mpl-2.0":                             false, // wrong case — MPL-2.0
	"MPL-1.0":                             true,
	"MPL-1.1":                             true,
	"MPL-2.0":                             true,
	"MPL-2.0-no-copyleft-exception":       true,
	"mplus":                               true,
	"MS-LPL":                              true,
	"MS-PL":                               true,
	"MS-RL":                               true,
	"MTLL":                                true,
	"MulanPSL-1.0":                        true,
	"MulanPSL-2.0":                        true,
	"Multics":                             true,
	"Mup":                                 true,
	"NAIST-2003":                          true,
	"NASA-1.3":                            true,
	"NBPL-1.0":                            true,
	"NCGL-UK-2.0":                         true,
	"NCSA":                                true,
	"Net-SNMP":                            true,
	"NetCDF":                              true,
	"Newsletr":                            true,
	"NGPL":                                true,
	"NICTA-1.0":                           true,
	"NIST-PD":                             true,
	"NIST-PD-fallback":                    true,
	"NIST-Software":                       true,
	"NLOD-1.0":                            true,
	"NLOD-2.0":                            true,
	"NLPL":                                true,
	"Nokia":                               true,
	"NOSL":                                true,
	"Noweb":                               true,
	"NPL-1.0":                             true,
	"NPL-1.1":                             true,
	"NPOSL-3.0":                           true,
	"NRL":                                 true,
	"NTP":                                 true,
	"NTP-0":                               true,
	"O-UDA-1.0":                           true,
	"OAR":                                 true,
	"OCCT-PL":                             true,
	"OCLC-2.0":                            true,
	"ODbL-1.0":                            true,
	"ODC-By-1.0":                          true,
	"OFFIS":                               true,
	"OFL-1.0":                             true,
	"OFL-1.0-no-RFN":                      true,
	"OFL-1.0-RFN":                         true,
	"OFL-1.1":                             true,
	"OFL-1.1-no-RFN":                      true,
	"OFL-1.1-RFN":                         true,
	"OGC-1.0":                             true,
	"OGDL-Taiwan-1.0":                     true,
	"OGL-Canada-2.0":                      true,
	"OGL-UK-1.0":                          true,
	"OGL-UK-2.0":                          true,
	"OGL-UK-3.0":                          true,
	"OGTSL":                               true,
	"OLDAP-1.1":                           true,
	"OLDAP-1.2":                           true,
	"OLDAP-1.3":                           true,
	"OLDAP-1.4":                           true,
	"OLDAP-2.0":                           true,
	"OLDAP-2.0.1":                         true,
	"OLDAP-2.1":                           true,
	"OLDAP-2.2":                           true,
	"OLDAP-2.2.1":                         true,
	"OLDAP-2.2.2":                         true,
	"OLDAP-2.3":                           true,
	"OLDAP-2.4":                           true,
	"OLDAP-2.5":                           true,
	"OLDAP-2.6":                           true,
	"OLDAP-2.7":                           true,
	"OLDAP-2.8":                           true,
	"OML":                                 true,
	"OpenPBS-2.3":                         true,
	"OpenSSL":                             true,
	"OPL-1.0":                             true,
	"OPL-UK-3.0":                          true,
	"OSET-PL-2.1":                         true,
	"OSL-1.0":                             true,
	"OSL-1.1":                             true,
	"OSL-2.0":                             true,
	"OSL-2.1":                             true,
	"OSL-3.0":                             true,
	"Parity-6.0.0":                        true,
	"Parity-7.0.0":                        true,
	"PDDL-1.0":                            true,
	"PHP-3.0":                             true,
	"PHP-3.01":                            true,
	"Plexus-Classworlds":                  true,
	"PolyForm-Noncommercial-1.0.0":        true,
	"PolyForm-Small-Business-1.0.0":       true,
	"PostgreSQL":                          true,
	"PSF-2.0":                             true,
	"psfrag":                              true,
	"psutils":                             true,
	"Python-2.0":                          true,
	"Python-2.0.1":                        true,
	"Qhull":                               true,
	"QPL-1.0":                             true,
	"QPL-1.0-INRIA-2004":                  true,
	"RHeCos-v1.1":                         true,
	"RPL-1.1":                             true,
	"RPL-1.5":                             true,
	"RPSL-1.0":                            true,
	"RSA-MD":                              true,
	"RSCPL":                               true,
	"Ruby":                                true,
	"SAX-PD":                              true,
	"Saxpath":                             true,
	"SCEA":                                true,
	"SchemeReport":                        true,
	"Sendmail":                            true,
	"Sendmail-8.23":                       true,
	"SGI-B-1.0":                           true,
	"SGI-B-1.1":                           true,
	"SGI-B-2.0":                           true,
	"SGP4":                                true,
	"SHL-0.5":                             true,
	"SHL-0.51":                            true,
	"SimPL-2.0":                           true,
	"SISSL":                               true,
	"Sleepycat":                           true,
	"SMLNJ":                               true,
	"SMPPL":                               true,
	"SNIA":                                true,
	"snprintf":                            true,
	"Spencer-86":                          true,
	"Spencer-94":                          true,
	"Spencer-99":                          true,
	"SPL-1.0":                             true,
	"SSH-OpenSSH":                         true,
	"SSH-short":                           true,
	"SSPL-1.0":                            true,
	"StandardML-NJ":                       true,
	"SugarCRM-1.1.3":                      true,
	"SWL":                                 true,
	"Symlinks":                            true,
	"TAPR-OHL-1.0":                        true,
	"TCL":                                 true,
	"TCP-wrappers":                        true,
	"TMate":                               true,
	"TOSL":                                true,
	"TPDL":                                true,
	"TPL-1.0":                             true,
	"TTWL":                                true,
	"TU-Berlin-1.0":                       true,
	"TU-Berlin-2.0":                       true,
	"UCAR":                                true,
	"UCL-2.0":                             true,
	"Unicode-DFS-2015":                    true,
	"Unicode-DFS-2016":                    true,
	"Unicode-TOU":                         true,
	"UnixCrypt":                           true,
	"Unlicense":                           true,
	"UPL-1.0":                             true,
	"Vim":                                 true,
	"VOSTROM":                             true,
	"VSL-1.0":                             true,
	"W3C":                                 true,
	"W3C-19980720":                        true,
	"W3C-20150513":                        true,
	"w3m":                                 true,
	"Watcom-1.0":                          true,
	"Widget-Workshop":                     true,
	"Wsuipa":                              true,
	"WTFPL":                               true,
	"wxWindows":                           true,
	"X11":                                 true,
	"X11-distribute-modifications-variant": true,
	"Xdebug-1.03":                         true,
	"Xerox":                               true,
	"Xfig":                                true,
	"XFree86-1.1":                         true,
	"xinetd":                              true,
	"xlock":                               true,
	"Xnet":                                true,
	"xpp":                                 true,
	"XSkat":                               true,
	"YPL-1.0":                             true,
	"YPL-1.1":                             true,
	"Zed":                                 true,
	"Zend-2.0":                            true,
	"Zimbra-1.3":                          true,
	"Zimbra-1.4":                          true,
	"Zlib":                                true,
	"zlib-acknowledgement":                true,
	"ZPL-1.1":                             true,
	"ZPL-2.0":                             true,
	"ZPL-2.1":                             true,
}

// IsValid reports whether expr is a valid SPDX license identifier or compound expression.
// Compound expressions use "AND", "OR", "WITH" operators and parentheses.
func IsValid(expr string) bool {
	expr = strings.TrimSpace(expr)
	if expr == "" {
		return false
	}
	return parseExpression(expr)
}

// parseExpression parses a compound SPDX expression.
func parseExpression(expr string) bool {
	// Remove outer parentheses if balanced
	expr = strings.TrimSpace(expr)

	// Split on top-level OR / AND / WITH
	// We use a simple token-based approach
	tokens := tokenise(expr)
	return evalTokens(tokens)
}

func tokenise(expr string) []string {
	var tokens []string
	var cur strings.Builder
	depth := 0
	for i := 0; i < len(expr); i++ {
		ch := expr[i]
		switch ch {
		case '(':
			depth++
			cur.WriteByte(ch)
		case ')':
			depth--
			cur.WriteByte(ch)
		case ' ':
			if depth == 0 {
				if cur.Len() > 0 {
					tokens = append(tokens, cur.String())
					cur.Reset()
				}
			} else {
				cur.WriteByte(ch)
			}
		default:
			cur.WriteByte(ch)
		}
	}
	if cur.Len() > 0 {
		tokens = append(tokens, cur.String())
	}
	return tokens
}

func evalTokens(tokens []string) bool {
	if len(tokens) == 0 {
		return false
	}

	// Find top-level OR / AND operators
	for i, tok := range tokens {
		if tok == "OR" || tok == "AND" {
			if i == 0 || i == len(tokens)-1 {
				return false
			}
			left := evalTokens(tokens[:i])
			right := evalTokens(tokens[i+1:])
			return left && right
		}
	}

	// Find top-level WITH operator
	for i, tok := range tokens {
		if tok == "WITH" {
			if i == 0 || i == len(tokens)-1 {
				return false
			}
			// WITH: left must be a valid license, right is an exception (we accept any non-empty string)
			left := evalTokens(tokens[:i])
			return left && len(tokens[i+1:]) > 0
		}
	}

	// Single token
	if len(tokens) == 1 {
		tok := tokens[0]
		// Handle parenthesised sub-expression
		if strings.HasPrefix(tok, "(") && strings.HasSuffix(tok, ")") {
			inner := tok[1 : len(tok)-1]
			return parseExpression(inner)
		}
		// Handle + suffix (or-later variant)
		tok = strings.TrimSuffix(tok, "+")
		// Check valid identifiers (only true entries)
		v, exists := validIdentifiers[tok]
		return exists && v
	}

	return false
}
