FROM registry.suse.com/bci/golang:latest AS builder
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN make embed-assets && \
    CGO_ENABLED=0 go build \
        -mod=vendor \
        -ldflags="-X main.serverVersion=0.2.0" \
        -o mcp-server-pcd \
        .

FROM scratch
COPY --from=builder /build/mcp-server-pcd /usr/bin/mcp-server-pcd
EXPOSE 8080
ENTRYPOINT ["/usr/bin/mcp-server-pcd", "http"]
