Name:           mcp-server-pcd
Version:        0.2.0
Release:        1%{?dist}
Summary:        PCD MCP server — templates, hints, lint, and milestone tools
License:        GPL-2.0-only
URL:            https://github.com/mge1512/pcd
Source0:        %{name}-%{version}.tar.xz
Source1:        %{name}-%{version}-vendor.tar.xz

# Source1 generated by:
#   go mod vendor && tar -cJf mcp-server-pcd-0.2.0-vendor.tar.xz vendor/

BuildRequires:  golang >= 1.22
BuildRequires:  make
BuildRequires:  pandoc
Recommends:     pcd-templates

%description
mcp-server-pcd is a Model Context Protocol (MCP) server for the Post-Coding
Development (PCD) workflow. It provides MCP tools and resources for:
  - Listing and retrieving PCD deployment templates
  - Listing and reading hints files and prompts
  - Linting PCD specification files (RULE-01 through RULE-17)
  - Setting milestone status in spec files

The binary is self-contained: all templates, hints, and prompts are embedded
at build time. Install pcd-templates to enable site-local asset overrides.

Supports stdio transport (for mcphost, Claude Desktop) and streamable-HTTP
transport (for web-based MCP hosts and remote access).

%prep
%autosetup -a 1

%build
make embed-assets
CGO_ENABLED=0 go build \
    -mod=vendor \
    -ldflags="-X main.serverVersion=%{version}" \
    -o %{name} \
    .
pandoc mcp-server-pcd.1.md -s -t man -o mcp-server-pcd.1

%install
install -D -m 0755 %{name} %{buildroot}%{_bindir}/%{name}
install -D -m 0644 mcp-server-pcd.service \
    %{buildroot}%{_unitdir}/mcp-server-pcd.service
install -D -m 0644 mcp-server-pcd.1 \
    %{buildroot}%{_mandir}/man1/mcp-server-pcd.1

%files
%license LICENSE
%doc README.md
%{_bindir}/%{name}
%{_unitdir}/mcp-server-pcd.service
%{_mandir}/man1/mcp-server-pcd.1*

%post
%systemd_post mcp-server-pcd.service

%preun
%systemd_preun mcp-server-pcd.service

%postun
%systemd_postun_with_restart mcp-server-pcd.service

%changelog
* Tue Apr 07 2026 Matthias G. Eckermann <pcd@mailbox.org> - 0.2.0-1
- Initial package release
